"use client";
import "./globals.css";
import { Inter } from "next/font/google";
import CustomNavbar from "@/components/CustomNavbar";
import { ToastContainer, toast } from "react-toastify";
import React, { useReducer } from "react";

import { initialState, reducer } from "../reducer/UseReducer.js";

const inter = Inter({ subsets: ["latin"] });

export const UserContext = React.createContext();

export const metadata = {
  title: "VRCS Live Menu",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const [state, dispatch] = useReducer(reducer, initialState);
  return (
    <html lang="en">
      {/* <body>
        <UserContext.Provider value = {{state, dispatch}}>
          <CustomNavbar />
          <ToastContainer />
          {children}
        </UserContext.Provider>
      </body> */}

      <body className={inter.className}>
        <UserContext.Provider value={{ state, dispatch }}>
          <CustomNavbar />
          <ToastContainer />
          {children}
        </UserContext.Provider>
      </body>
    </html>
  );
}
